# Generated by Django 5.2.17 on 2026-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_backfill_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("rw", "Kinyarwanda")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="privacy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="privacy_policy_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
