# Generated by Django 5.2.17 on 2026-09-13 10:08

import apps.morning_devotions.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0002_article_review_note_article_reviewed_at_and_more"),
        ("devotions", "0002_devotion_published_at_devotion_review_note_and_more"),
        ("podcasts", "0003_alter_episode_audio_file"),
        ("videos", "0003_alter_video_video_file_alter_video_youtube_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MorningDevotionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title_en", models.CharField(max_length=200)),
                ("title_rw", models.CharField(max_length=200)),
                ("scripture_reference", models.CharField(blank=True, max_length=120)),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Shown before the session — what to expect.",
                    ),
                ),
                ("description_rw", models.TextField(blank=True)),
                (
                    "summary_en",
                    models.TextField(
                        blank=True,
                        help_text="Written afterward, once the session is finished.",
                    ),
                ),
                ("summary_rw", models.TextField(blank=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "meet_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            apps.morning_devotions.validators.validate_meet_url
                        ],
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("rw", "Kinyarwanda"),
                            ("bilingual", "Bilingual"),
                        ],
                        default="en",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recording_episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="morning_devotion_sessions",
                        to="podcasts.episode",
                    ),
                ),
                (
                    "recording_video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="morning_devotion_sessions",
                        to="videos.video",
                    ),
                ),
                (
                    "related_devotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="morning_devotion_sessions",
                        to="devotions.devotion",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="morning_devotion_sessions",
                        to="articles.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Morning Devotion session",
                "verbose_name_plural": "Morning Devotion sessions",
                "ordering": ["-start_datetime"],
            },
        ),
    ]
