# Generated by Django 5.2.17 on 2026-09-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BeliefPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=150)),
                ("title_rw", models.CharField(max_length=150)),
                ("description_en", models.TextField()),
                ("description_rw", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CallTimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                (
                    "body_en",
                    models.TextField(
                        help_text="An independent English retelling — not a translation."
                    ),
                ),
                (
                    "body_rw",
                    models.TextField(
                        help_text="Preserve the founder's original Kinyarwanda wording verbatim."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Call timeline entry",
                "verbose_name_plural": "Call timeline entries",
                "ordering": ["order", "year"],
            },
        ),
        migrations.CreateModel(
            name="SevenMountain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_rw", models.CharField(max_length=100)),
                ("description_en", models.TextField()),
                ("description_rw", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("flame", "Flame"),
                            ("river", "River"),
                            ("mountain", "Mountain"),
                            ("book", "Book"),
                            ("mic", "Microphone"),
                            ("gavel", "Gavel"),
                            ("mask", "Mask"),
                            ("cap", "Graduation cap"),
                            ("heart", "Heart"),
                            ("coin", "Coin"),
                            ("shield", "Shield"),
                            ("wave", "Wave"),
                            ("pin", "Pin"),
                            ("play", "Play"),
                            ("chevdown", "Chevron down"),
                        ],
                        default="mountain",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
