# Generated by Django 5.2.17 on 2026-09-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Devotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("verse_ref", models.CharField(max_length=120)),
                ("verse_text_en", models.TextField()),
                ("verse_text_rw", models.TextField()),
                ("reflection_en", models.TextField()),
                ("reflection_rw", models.TextField()),
                ("prayer_en", models.TextField()),
                ("prayer_rw", models.TextField()),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as 'Today's Devotion'. If none is marked, the most recent by date is used.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
