# Generated by Django 5.2.17 on 2026-09-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_sitesettings_morning_devotion_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="website_url",
            field=models.URLField(
                blank=True,
                help_text="Shown in the footer of generated devotional share images, e.g. https://youthtimerevival.rw",
            ),
        ),
    ]
