# Generated by Django 5.2.17 on 2026-09-01 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PodcastSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title_en", models.CharField(max_length=150)),
                ("title_rw", models.CharField(max_length=150)),
                ("subtitle_en", models.CharField(blank=True, max_length=250)),
                ("subtitle_rw", models.CharField(blank=True, max_length=250)),
                ("description_en", models.TextField(blank=True)),
                ("description_rw", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="podcasts/"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("flame", "Flame"),
                            ("river", "River"),
                            ("mountain", "Mountain"),
                            ("book", "Book"),
                            ("mic", "Microphone"),
                            ("gavel", "Gavel"),
                            ("mask", "Mask"),
                            ("cap", "Graduation cap"),
                            ("heart", "Heart"),
                            ("coin", "Coin"),
                            ("shield", "Shield"),
                            ("wave", "Wave"),
                            ("pin", "Pin"),
                            ("play", "Play"),
                            ("chevdown", "Chevron down"),
                        ],
                        default="mic",
                        max_length=30,
                    ),
                ),
                ("color", models.CharField(default="#E4572E", max_length=20)),
                ("spotify_url", models.URLField(blank=True, null=True)),
                ("apple_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Podcast series",
                "ordering": ["order", "title_en"],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_rw", models.CharField(max_length=200)),
                ("description_en", models.TextField(blank=True)),
                ("description_rw", models.TextField(blank=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g. '11 min'", max_length=20
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="episodes/"),
                ),
                ("audio_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="podcasts.podcastseries",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
