# Generated by Django 5.2.17 on 2026-09-01

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0002_episode_published_at_episode_review_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="episodes/",
                validators=[apps.core.uploads.validate_audio_upload],
            ),
        ),
    ]
