# Generated by Django 5.2.17 on 2026-09-01 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title_en", models.CharField(max_length=150)),
                ("title_rw", models.CharField(max_length=150)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("flame", "Flame"),
                            ("river", "River"),
                            ("mountain", "Mountain"),
                            ("book", "Book"),
                            ("mic", "Microphone"),
                            ("gavel", "Gavel"),
                            ("mask", "Mask"),
                            ("cap", "Graduation cap"),
                            ("heart", "Heart"),
                            ("coin", "Coin"),
                            ("shield", "Shield"),
                            ("wave", "Wave"),
                            ("pin", "Pin"),
                            ("play", "Play"),
                            ("chevdown", "Chevron down"),
                        ],
                        default="flame",
                        max_length=30,
                    ),
                ),
                ("color", models.CharField(default="#241A3D", max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Video series",
                "ordering": ["order", "title_en"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_rw", models.CharField(max_length=200)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="videos.videoseries",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
