# Generated by Django 5.2.17 on 2026-09-01

import apps.core.uploads
import apps.videos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_published_at_video_review_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[apps.core.uploads.validate_video_upload],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[apps.videos.validators.validate_youtube_url],
            ),
        ),
    ]
