# Generated by Django 5.2.17 on 2026-09-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_en", models.CharField(max_length=300)),
                ("question_rw", models.CharField(max_length=300)),
                ("answer_en", models.TextField()),
                ("answer_rw", models.TextField()),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Shown as the 'Most Asked' highlight card. Only one should be marked.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "id"],
            },
        ),
    ]
