# Generated by Django 5.2.17 on 2026-09-01 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("bio_en", models.TextField(blank=True)),
                ("bio_rw", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="authors/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title_en", models.CharField(max_length=200)),
                ("title_rw", models.CharField(max_length=200)),
                ("hook_en", models.CharField(max_length=300)),
                ("hook_rw", models.CharField(max_length=300)),
                (
                    "body_en",
                    models.TextField(help_text="Paragraphs separated by a blank line."),
                ),
                (
                    "body_rw",
                    models.TextField(help_text="Paragraphs separated by a blank line."),
                ),
                ("verse_text_en", models.TextField(blank=True)),
                ("verse_text_rw", models.TextField(blank=True)),
                ("verse_ref_en", models.CharField(blank=True, max_length=120)),
                ("verse_ref_rw", models.CharField(blank=True, max_length=120)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("flame", "Flame"),
                            ("river", "River"),
                            ("mountain", "Mountain"),
                            ("book", "Book"),
                            ("mic", "Microphone"),
                            ("gavel", "Gavel"),
                            ("mask", "Mask"),
                            ("cap", "Graduation cap"),
                            ("heart", "Heart"),
                            ("coin", "Coin"),
                            ("shield", "Shield"),
                            ("wave", "Wave"),
                            ("pin", "Pin"),
                            ("play", "Play"),
                            ("chevdown", "Chevron down"),
                        ],
                        default="flame",
                        max_length=30,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#241A3D",
                        help_text="Hex color used behind the icon when there is no cover image.",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="articles.author",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
